name: Check
on:
  push:

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            latex-bin tools alphalph metalogo hyperref infwarerr amsmath amsfonts booktabs
            colortbl hologo pdftexcmds iftex kvoptions enumitem psnfss csquotes fancyvrb
            underscore metafont ec hypdoc
      - name: "Enable bootstrapping intopdf.sty"
        run: |
          echo "\newcommand{\attachandlink}[4][x]{BOOTSTRAP-MODE}" > intopdf.sty
      - run: pdflatex intopdf.dtx
      - run: pdflatex intopdf.dtx
      - run: pdflatex example.tex
      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: "*.pdf"
